name: pixa_project
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  uuid: ^4.4.0
  flutter_cache_manager: ^3.3.1
  dio: ^5.1.2
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.3.2
  easy_localization: ^3.0.8
  go_router: ^17.0.0
  adaptive_theme: ^3.7.2
  toastification: ^3.0.3
  collection:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  flutter_gen_runner:
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/translations/en.json
    - assets/images/
    - lib/utils/.env


flutter_native_splash:
  color: "#FFFFFF"
  android_12:
    image: assets/images/security.png
  image: assets/images/security.png
  color_dark: "#FFFFFF"
  image_dark: assets/images/security.png
  android: true
  ios: true

flutter_icons:
  android: "ic_launcher"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/security.png"